AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - "Gemfile"
    - "Rakefile"
    - "bin/**/*"
    - "config/**/*"
    - "db/schema.rb"
    - "db/seeds.rb"
    - "db/migrate/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"

plugins:
  - rubocop-rails
  - rubocop-performance

Layout/LineLength:
  Max: 100

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "config/routes.rb"
    - "config/environments/*.rb"

Style/Documentation:
  Enabled: false
